/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface RemoteConfigGlobals {
  something: string;
}

export interface RemoteConfigRaw {
  globals: RemoteConfigGlobals;
}
