name: Deploy config
description: Deploy config to the specified environment
inputs:
  env:
    description: 'Environment to deploy to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print env details
      shell: bash
      run: |
        echo "Deploying ${{ inputs.env }} config..."
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: '22'
    # - name: Install dependencies
    #   shell: bash
    #   run: npm i
