name: Deploy config
description: Deploy config to the specified environment
inputs:
  env:
    description: 'Environment to deploy to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.11.0
      env:
        ENV_NAME: ${{ inputs.env }}
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: Luke-Rogerson, crypto-perry
        minimum-approvals: 1
        issue-title: 'Deploy config to ${ENV_NAME}'
        issue-body: 'Please approve or deny the deployment of config to ${ENV_NAME}.'
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: '22'
    # - name: Install dependencies
    #   shell: bash
    #   run: npm i
