name: Deploy config
description: Deploy config to the specified environment
inputs:
  env:
    description: 'Environment to deploy to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print env details
      shell: bash
      run: |
        echo "Deploying ${{ inputs.env }} config..."
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.11.0
      with:
        secret: ${{ github.TOKEN }}
        approvers: Luke-Rogerson, crypto-perry
        minimum-approvals: 1
        issue-title: 'Deploy config to ${{ inputs.env }}'
        issue-body: 'Please approve or deny the deployment of config to ${{ inputs.env }}.'
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: '22'
    # - name: Install dependencies
    #   shell: bash
    #   run: npm i
