name: Config Build Pipeline

on:
  push:
    paths:
      - "config/**"
      - "src/schema.ts"
  pull_request:
    paths:
      - "config/**"
      - "src/schema.ts"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      base-changed: ${{ steps.changes.outputs.base }}
      staging-changed: ${{ steps.changes.outputs.staging }}
      prod-changed: ${{ steps.changes.outputs.prod }}
      utils-changed: ${{ steps.changes.outputs.utils }}
      schema-changed: ${{ steps.changes.outputs.schema }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            staging:
              - 'config/staging.ts'
              - 'config/base.ts'
              - 'config/utils.ts'
            prod:
              - 'config/prod.ts'
              - 'config/base.ts'
              - 'config/utils.ts'

  build-staging:
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.staging-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm i
      - name: Build and output staging config JSON
        run: |
          echo "🔧 Building staging configuration..."
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Files in config/: $(ls -la config/)"
          echo ""
          echo "📄 STAGING CONFIG JSON OUTPUT:"
          echo "================================"
          npm run build:staging
          echo "================================"
          echo "✅ Staging configuration built successfully!"

  build-prod:
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.prod-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm i
      - name: Build and output prod config JSON
        run: |
          echo "🔧 Building production configuration..."
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo ""
          echo "📄 PRODUCTION CONFIG JSON OUTPUT:"
          echo "=================================="
          npm run build:prod
          echo "=================================="
          echo "✅ Production configuration built successfully!"
