name: Config Build Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'src/schema.ts'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      staging-changed: ${{ steps.changes.outputs.staging }}
      prod-changed: ${{ steps.changes.outputs.prod }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dev:
              - 'config/base/**'
              - 'config/environments/dev/**'
            staging:
              - 'config/base/**'
              - 'config/environments/staging/**'
            prod:
              - 'config/base/**'
              - 'config/environments/prod.ts'

  staging:
    name: Build, validate and deploy staging config
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.staging-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm i
      - name: Generate config
        run: npm run generate-configs
      - name: Validate config
        run: npm run validate-configs
